name: Deploy to Production
on: 
  push: 
    branches: 
      - main
jobs: 
  deploy: 
    runs-on: ubuntu-latest 
    steps: 
      - name: Checkout code 
        uses: actions/checkout@v4 
      - name: Setup SSH key 
        uses: webfactory/ssh-agent@v0.8.0 
        with: ssh-private-key: ${{ secrets.PROD_SSH_KEY }} 
      - name: Push to production server 
        run: | 
          git remote add prod banana@143.198.147.148:/var/repo/CSE-135-HW1.git 
          git push prod main
